# -*- coding: utf-8 -*-

from . import product_template
from . import sale_order
from . import sale_order_line
from . import res_partner
from . import purchase_order
from . import purchase_order_line
from . import maintenance_equipment
from . import account_move
from . import maintenance_version
from . import maintenance_etapes_pret
from . import account_partner_cat
from . import naf_code
from . import res_company
from . import helpdesk_ticket
from . import helpdesk_source
from . import ticket_gamme
from . import hr_attendance
from . import stock_move
from . import stock_picking
from . import product_pricelist
from . import product_pricelist_item
from . import maintenance_request
from . import stock_quant
from . import oci_helpdesk_type_ticket
from . import family
from . import stock_lot
from . import product
from . import lot_motif_retrait
from . import immuno_hemato
from . import product_supplierinfo
from . import regroupement
from . import contact_roles
from . import centre_interet
from . import service
from . import code_affaire
from . import equipement_cmf
from . import automates_client
from . import automates_bm_clients