# -*- coding: utf-8 -*-


{
    "name": "IBJB Studio",
    "version": "17.0.1.0.0",
    "category": "IBJB Studio",
    "summary": "IBJB Studio",
    "description": """
        Convert all studio customization to code""",
    "author": "Aktic software",
    "website": "http://www.aktivsoftware.com",
    "category": "Studio customization",
    "version": "17.0.1.0.0",
    "license": "LGPL-3",
    "depends": [
        "sale_subscription",
        "maintenance",
        "contacts",
        "account_followup",
        "delivery",
        "product",
        "purchase",
        "hr",
        'sale_management',
        'helpdesk',
        'l10n_fr',
        'project',
        'crm',
        'account',
        'hr_attendance',
        'stock',
        'sale_stock',
        'stock_delivery',
        'purchase_stock',
        'product_expiry',
        'stock_barcode',
        'web'
    ],
    "data": [
        "security/ir.model.access.csv",
        "security/maintenance_security.xml",
        "data/action_add_fields.xml",
        "data/hr_mail_template.xml",
        "data/helpdesk_mail_template.xml",
        "data/helpdesk_server_actions.xml",
        "data/attendance_ir_actions_server.xml",
        "data/account_ir_action_server.xml",
        "data/product_ir_action_server.xml",
        "data/stock_ir_action_server.xml",
        "views/maintenance_version_views.xml",
        "views/maintenance_etapes_pret_views.xml",
        "views/hr_employee_views.xml",
        "views/sale_order_views.xml",
        "views/account_partner_cat_views.xml",
        "views/naf_code_views.xml",
        "views/account_move_views.xml",
        "views/sale_subscription_views.xml",
        "views/maintenance_equipment_views.xml",
        "views/partner_view.xml",
        "views/purchase_views.xml",
        "views/res_company_views.xml",
        "views/helpdesk_ticket_views.xml",
        "views/helpdesk_ticket_type_views.xml",
        "views/helpdesk_source_views.xml",
        "views/ticket_gamme_views.xml",
        "views/res_users_views.xml",
        "views/hr_attendance_views.xml",
        "views/res_partner_views.xml",
        "views/stock_picking_views.xml",
        "views/product_pricelist_views.xml",
        "views/maintenance_request_views.xml",
        "views/oci_helpdesk_type_ticket.xml",
        "views/family_views.xml",
        "views/immuno_hemato_views.xml",
        "views/product_template_views.xml",
        "views/stock_quant_views.xml",
        "views/lot_motif_retrait_views.xml",
        "views/stock_lot_views.xml",
        "report/product_pricelist_copy_1.xml",
        "report/transfer_report_1.xml",
        "report/transfer_report_2.xml",
        "report/transfer_report_3.xml",
        "report/maintenance_equipment_reports_templates.xml",
        "report/maintenance_equipments_reports_actions.xml",
        "report/report_purchase.xml",
        "report/ir_actions_report_templates.xml",
        "report/stock_paperformat.xml",
        "report/picking_operations.xml",
        "report/stock_picking_reports_actions.xml",
        "report/report_picking_copy_2.xml",
        "report/transfer_report_copy(1).xml",
        "report/picking_operations_copy_4.xml",
        "report/transfer_report_copy(2).xml",
        "report/account_move_reports_templates.xml",
        "report/account_move_reports_actions.xml",
        "report/sale_report_view.xml",
        "report/product_pricelist_priceoffer.xml",
        "report/product_pricelist_actions.xml",
        "report/maintenance_request_reports_templates.xml",
        "report/maintenance_request_reports_actions.xml",
        "report/report_stockinventory.xml",
    ],
    "installable": True,
    "auto_install": False,
    "application": False,
}
